### ISSUE TITLE
Not working on RPi

### ISSUE THREAD

**Issue by MissPhilbin** [topshed/RPi_8x8GridDraw#2]
Hi there, I wanted to give this wonderful software a try as part of a Rpi workshop I am giving. However running it on the command line on Raspbian Jessie does not work. Python pumps out a whole load of inconsistent use of tabs and spaces in indentation errors. Is there a quick fix other than working all through the code to remove the tabs and replace with 4 spaces? Thanks.

For the time being we are going to work on @mrichardson23's branch.

**Comment by topshed** [comment]
Weird. I've tried it on a fresh install of jessie and it worked fine for me. Can you post a dump of the errors please.

**Comment by topshed** [comment]
I've been through all the .pys and converted all tabs to 4 spaces, and then back again. Tested on Wheezy and jessie. Please try this latest version and let me know if you're still having problems. Thanks.

**Comment by topshed** [comment]
Very old issue !
