### ISSUE TITLE
Option to run without a hat?

### ISSUE THREAD

**Issue by DaddyTheRunner** [topshed/RPi_8x8GridDraw#3]
I would like to be able to try out this program without access to a hat.  I'm waiting for my SenseHat to arrive and would like to play with the grid draw program.  However, when I try to run it, it complains about not finding a SenseHat.

Can you suggest options for commenting out the code that calls the hat?  Would doing that break the rest of the code?

**Comment by DaddyTheRunner** [comment]
I think I answered my own question.  I was able to add a check for the SenseHat module and then ignored calls to the SenseHat object if it wasn't present.

I'm not sure what would happen if the python module exists but the Sense Hat isn't physically installed on the RPi.

I'll generate a pull request with my simple modifications.

**Comment by topshed** [comment]
The new version using guizero has the ability to run without a sensehat built in
