### ISSUE TITLE
Frame 0

### ISSUE THREAD

**Issue by crocodile54** [topshed/RPi_8x8GridDraw#6]
I deleted all the frames and then went to clear the frame on the screen green, it came up fully green on the sense hat however only one frame went green on the editor.

**Comment by crocodile54** [comment]
Also if I delete two of my two frames it appeares either as frame 002 of 001 or as frame 000 of 001.

**Comment by topshed** [comment]
The issue with incorrect frame numbering after deletion has been fixed. This has also fixed the single pixel issue which was related to the same problem.
